datasources.default.allow-pool-suspension=true
datasources.default.url=jdbc\:postgresql\://postgres\:5432/notesdb
datasources.default.driver-class-name=org.postgresql.Driver
micronaut.application.name=demo
